import "./globals.css";
import Footer from "./_layout/footer";
import Header from "./_layout/header";

export const metadata = {
  title: process.env.APP_NAME || "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
